name: trimajadi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoapp.png" 
  adaptive_icon_foreground: "assets/images/logoapp.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/desain.jpeg
    - assets/images/edukasi.jpeg
    - assets/images/pemrograman.jpeg
    - assets/images/visual_audio.jpeg
    - assets/images/pemrograman.jpeg
    - assets/images/desain_logo.jpeg
    - assets/images/web_development.jpeg
    - assets/images/video_editing.jpeg
    - assets/images/penulisan.jpeg
    - assets/images/logoapp.png
